config.yaml, metadata.yaml, requirements.txt, src/charm.py, src/templates/vault.hcl.j2, test-requirements.txt, tests/unit/config.hcl, tests/unit/config_with_raft_peers.hcl, tests/unit/config_with_raft_peers_equivalent.hcl, tests/unit/test_charm.py
This PR includes the what is needed to create a barebone vault configuration file needed to run the Vault server. The file is being placed in the `/var/snap/vault/common/` directory where the snap can have access to it.
The current version of the config file does not yet contain TLS Certificates and the complete Raft configuration. This was intentional in order to make this PR smaller.  Those will come in follow-up PR's.
=> feat: Creates vault config.hcl file

.github/workflows/main.yaml, .github/workflows/publish-charm.yaml, metadata.yaml, tests/unit/config.hcl
Until this charm is published to the [official Vault Charm on Charmhub](https://charmhub.io/vault) and that we have a 1.15 track for it, we still want to publish it somewhere, for development, documentation and workflow standardisation purposes.
I created a new `vault-dev` charm on charmhub to serve this purpose as well as a the necessary CI workflows to publish the charm there.
As soon as we have the new track created and alignement with the Openstack team, we shall point to the appropriate charm on Charmhub.
=> chore: Add publishing workflow

.github/workflows/main.yaml, .github/workflows/publish-charm.yaml
The was an issue with PR #13 where we would assume the charm had been built before but actually wasn't. Here we have the  `canonical/charming-actions/upload-charm` workflow build the charm.
=> fix: Build charm before publishing it

README.md, src/charm.py, src/templates/vault.hcl.j2, tests/unit/config.hcl, tests/unit/test_charm.py
We add the retry join stanza to Vault's configuration file based on addresses shared through peer relation.
This change does not contain anything related to TLS certificates, this will come in a follow-up PR.
=> feat: Adds retry join to vault config

.github/workflows/integration-tests.yaml, .github/workflows/main.yaml, .github/workflows/publish-charm.yaml, test-requirements.txt, tests/integration/test_integration.py, tox.ini
Add integration tests scaffolding:
- CI workflow that runs tests on every PR and push to main
- Minimal integration test that simply builds the charm, deploys it and waits for it to be active
- More integration tests will come up as we improve the charm but at least we got the scaffolding here now.
=> test: Add integration tests scaffolding

charmcraft.yaml, lib/charms/grafana_agent/v0/cos_agent.py, metadata.yaml, requirements.txt, src/charm.py, test-requirements.txt, tests/integration/test_integration.py
The `prometheus-scrape` interface is intended to be used with k8s charms, for machine charms we should use `cos-agent`
Implements the `cos-agent` interface as a provider:
- Adds the integration to the metadata.yaml
- Adds requirements
- Adds a simple integration test case
=> feat: Implements the `cos-agent` interface as a provider

metadata.yaml, src/charm.py, src/machine.py, src/templates/vault.hcl.j2, tests/unit/config.hcl, tests/unit/test_charm.py
Now that the Vault snap supports the vaultd daemon service, we start this service as part of the deployment of the Vault charm.
We have to use the `latest/edge` track of the snap for the moment as it is the only one that contains the daemon. As we move it to its own track and promote it, we should eventually switch from `latest/edge` to `1.15/stable`.
=> feat: Start vaultd service

tests/integration/test_integration.py
Use `in` operator so that logic is applied correctly. Previous code would always return true.
=> test: Fix for integration test

pyproject.toml
This removes some warnings about deprecated config keys.
=> chore: Fix ruff warnings

src/charm.py, tests/unit/test_charm.py
This prevents two things:
1. Don't display the status message "Installing Vault" every time configure is run (unless we're actually installing Vault)
2. Stop spamming logs that say we're installing vault every time configure is run. 
Also refactors tests to use `MagicMock` instead of our own `MockSnapObject`
=> fix: Don't display installing vault when we're not

.github/workflows/main.yaml, .github/workflows/publish-charm.yaml, README.md, metadata.yaml, tests/unit/config.hcl
This PR aims to publish the charm on track `1.15` under the [vault](https://charmhub.io/vault) charm.
=> chore: Uses track 1.15 to publish the charm

pyproject.toml
For whatever reason, dependabot appears to expect the pyproject.toml to be in this format. This should get dependabot working again.
Related; https://github.com/canonical/vault-k8s-operator/pull/188
=> chore: Change formatting of pyproject.toml

lib/charms/operator_libs_linux/v2/snap.py, lib/charms/tls_certificates_interface/v3/tls_certificates.py, lib/charms/vault_k8s/v0/vault_tls.py, pyproject.toml, src/charm.py, tests/unit/test_charm.py
Use collect status to centralise status management. We will need this change to implement the `vault-pki` behavior as it was done in the K8s version of the charm. 
We also bump the charm libs version as recent changes in vault_k8s lib were used here.
=> chore: use collect status to centralise status management

requirements.in, requirements.txt
Reverts canonical/vault-operator#69 -- didn't pass tests but was auto-merged
=> fix: Revert "chore: Bump pydantic from 1.10.14 to 2.6.4"

src/charm.py, tests/unit/test_charm.py
This cuts the waiting time significantly when multiple Vault units are started on initial deploy. Before this change, all units that were not the leader would wait until the leader had finished installing Vault before they would install Vault.
As part of this, some fixes needed to be made to the tests.
- The snap cache wasn't being mocked properly, and was attempting to install the snap on the machine running the tests. This change mocks the snap cache at the class level to avoid mishaps in the future.
- The vault TLS manager is mocked on set-up for the same reason -- to avoid accidental calls to the external library. For some reason this worked for the TLS manager, but not the snap cache. I'm not entirely sure why.
- `test_given_unit_is_leader_and_ca_certificate_saved_when_collectstatus_t …
=> perf: Install the Vault snap immediately

src/charm.py
This allows us to temporarily set the status of the charm during a long running operation, and then restore it to the previous state once the operation is complete.
Before this change, the "Installing Vault" status message would continue to be set for the remainder of the hook.
=> fix: Add temp_maintenance_status contextmanager

lib/charms/vault_k8s/v0/vault_tls.py, src/machine.py
Auto-update libs workflow isn't working because of a permission error I haven't resolved yet, but also this needs manual intervention since `restart()` needs to be implemented to pass the tests anyway. 
This is yet another pre-requisite to get #62 working properly with TLS certificates.
=> chore: Update `vault_tls`, implement `restart()`

tests/integration/test_integration.py, tox.ini
Not providing any parameters only validates the code in `src/`  -- this change adds the tests to the code validated by `pyright`
=> build: Validate tests with pyright

config.yaml, metadata.yaml, src/charm.py, src/templates/charm_policy.hcl, tests/integration/test_integration.py, tests/unit/test_charm.py
Vault can now act as an intermediate CA where the parent CA is the provider side of the newly added tls-certificates-pki integration. Here we add the requirer side of the pki integration .
Upon certificates-pki-request relation joined:
- Configure the PKI mount, configures the PKI intermediate CA (generates a CSR)
- Send that CSR over to the relation provider.
- Store the CSR in a Juju secret
Upon Certificate Available:
- Validate that the received cert matches the stored CSR
- Set the PKI intermediate CA certificate
- Set the PKI charm role
1. This task is the equivalent of this one made in the K8s charm: 
- https://github.com/canonical/vault-k8s-operator/pull/180
2. A follow up PR will implement the provider side where requires will be able to integrate with Vault using the …
=> feat: implement upstream side of pki integration

.github/ISSUE_TEMPLATE/bug_report.md
Use labels in issue template. Here I copied the template from the k8s version of the charm.
=> chore: use `bug` label in issue template

metadata.yaml, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
In #87 , we added the "upstream" side of the PKI integration. Here we add the "downstream" side that TLS requirers can use to request TLS certificates. Vault will treat those requests using the PKI secrets engine. This is accomplished using the `tls-certificates` interface which we alias to `vault-pki` here to standardise with `vault-transit` and `vault-kv`.
Deploy Vault
```
juju deploy vault -n 3 --config common_name=mydomain.com
```
Deploy the parent CA
```
juju deploy self-signed-certificates
```
Integrate Vault with its parent CA
```
juju integrate vault:tls-certificates-pki self-signed-certificates
```
Deploy tls-certificates-requirer
```
juju deploy tls-certificates-requirer --common_name=demo.mydomain.com
```
Integrate TLS Certificates Requirer with Vault
```
juju integrate …
```
=> feat: implement downstream side of pki integration

actions.yaml, lib/charms/data_platform_libs/v0/s3.py, metadata.yaml, requirements.in, requirements.txt, src/charm.py, src/s3_session.py, test-requirements.txt, tests/integration/helpers.py, tests/integration/test_integration.py, tests/unit/test_charm.py, tests/unit/test_s3_session.py, tox.ini
Implement raft backup action using the `s3` charm relation interface.
```
juju deploy s3-provider
juju integrate vault:s3-parameters <s3 provider>
juju run vault/leader create-backup
```
The `s3_session` implementation is slightly different from the k8s version of the charm here:
- We don't bubble up exceptions from boto3 and use custom exceptions instead.
- We use typing coming from `boto3-stubs`
- We implement small private helpers (`_bucket_exists`, `_create_bucket`)
We likely want to combine this code into a charm library and have this imported in the two versions of the charm, I didn't want to impact the ongoing efforts in the k8s charm at that moment and decided against it for the moment.
The integration tests here don't validate end-to-end s3 backup because there is no minio …
=> feat: implement backup action

actions.yaml, src/charm.py, src/s3_session.py, tests/integration/test_integration.py, tests/unit/test_charm.py, tests/unit/test_s3_session.py
Implement raft `list-backups` action using the `s3` charm relation interface. This is a follow-up to #108 .
```
juju deploy s3-provider
juju integrate vault:s3-parameters <s3 provider>
juju run vault/leader list-backups
```
The integration tests here don't validate end-to-end s3 backup because there is no minio machine charm or any other machine charm that supports the s3 charm relation interface. So we simply validate that the `list-backups` action fails, as expected with the bad endpoint we provide it. This is likely something we want to improve in the future as the s3 situation on machine charms improve.
The `restore` backup action will be implemented in independent PR's to keep PR reviewable, this one was large enough as it is.
=> feat: implement `list-backups` action

.github/workflows/build.yaml, .github/workflows/integration-tests.yaml
Charmcraft currently does not work with the latest lxd version (5.21/stable). This prevents multiple PR's being merged. This change freezes lxd to 5.20/stable. 
- https://github.com/canonical/charmcraft/issues/1640
=> fix: freeze lxd to 5.20/stable

tests/unit/test_charm.py
Ops recently added support for running actions using the run_action method. This allows for triggering action events without directly making calls to the event handlers. In practice this also means we can refactor the handlers names without breaking tests. This is only a change in unit tests.
=> chore: use ops.testing.run_action instead of directly calling event handlers

src/charm.py, tests/unit/test_charm.py
Currently there is no output for the authorise-charm action when it is successful.
I think it is better to have a clear feedback when the action succeeds especially because some Juju versions fail to show failure messages.
=> chore: Adds action result for authorise charm action

src/charm.py, src/grafana_dashboards/vault.json
Add Grafana dashboard for Vault with the same panels as in the Kubernetes charm*.
Currently this dashboard is identical to the K8s dashboard except that it does not contain a panel for audit logs. We don't use pebble here and audit logs show up as if they came from the Grafana Agent charm. This should likely be figured out on its own.
=> feat: add grafana dashboard

src/charm.py, src/loki_alert_rules/error_logs_found.rule, src/prometheus_alert_rules/failure_tolerance.rule, src/prometheus_alert_rules/leader_last_contact.rule, src/prometheus_alert_rules/leadership_setup_failure.rule, src/prometheus_alert_rules/vault_sealed.rule
Adds Prometheus alert rules following spec TE071.
To test deploy the charm from this branch and follow the [guide on how to integrate with COS](https://charmhub.io/vault/docs/h-integrate-with-cos?channel=1.15/beta), go to the alerts tabs in Grafana and then:
- To test the vault sealed rule, seal and unseal vault and observe the alert firing
- To test the leader last contact rule, reduce the threshold to something very small, maybe 5 ms and observe the alert firing
- To test the failure tolerance rule scale vault up to 3 units then back to 2 units and observe the alert firing
- I couldn't find a way to simulate leadership setup failure
=> feat: Adds Prometheus alert rules

charmcraft.yaml, lib/charms/vault_k8s/v0/vault_client.py, src/charm.py, tests/unit/test_charm.py
This PR introduces the same changes as https://github.com/canonical/vault-k8s-operator/pull/377 that was merged in the k8s charm.
- Fetches the latest vault_client lib
- Fixes: https://github.com/canonical/vault-k8s-operator/issues/367 in the charm code
- When the common name is changed a new CSR will be generated to get a new intermediate CA that will replace the old one and the pki role will be updated too.
- Adds unit tests
=> fix: Update intermediate CA and PKI role when common_name is changed

lib/charms/vault_k8s/v0/vault_client.py, src/charm.py, tests/integration/test_integration.py, tests/integration/vault.py, tests/unit/test_charm.py
Fetches the changes made to the vault client lib in [this PR](https://github.com/canonical/vault-k8s-operator/pull/386) and applies required change like in that PR and adds tests.
=> chore: Fetches latest vault client lib and applies required changes

tests/integration/conftest.py, tests/integration/test_integration.py, tests/integration/vault.py, tests/integration/vault_kv_requirer_operator/src/charm.py, tests/unit/test_charm.py, tox.ini
Currently, ruff is only configured to check the files for linting errors. This adds ruff formatting to tox checks.
This explains some of the inconsistencies we have had with the formatting, as it depended on how a person's editor was configured.
Review notes:
Only [`tox.ini`](https://github.com/canonical/vault-operator/pull/212/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449) contains functional changes, the rest are the result of running `tox -e format`.
=> style: Format using `ruff`

src/charm.py, tests/unit/test_charm.py
Part of the recent changes to `vault_client` removed the default to `token_ttl` and `token_max_ttl`. This means they both need to be set where we were expecting the defaults.
=> fix: Set token ttl

charmcraft.yaml, lib/charms/vault_k8s/v0/vault_autounseal.py, lib/charms/vault_k8s/v0/vault_client.py, src/charm.py, src/templates/autounseal_policy.hcl, src/templates/charm_policy.hcl, src/templates/vault.hcl.j2, tests/integration/helpers.py, tests/integration/test_integration.py, tests/integration/vault.py, tests/unit/test_charm.py
Requires: https://github.com/canonical/vault-k8s-operator/pull/403
Implements the machine charm version of auto-unseal. See https://github.com/canonical/vault-k8s-operator/pull/365 for the k8s charm implementation. Usage is exactly the same as in the k8s charm, however, now cross-model relations are possible. In other words, you can use a machine Vault to unlock a k8s Vault (or vice-versa).
To do that:
1. Deploy your unsealer and autounsealed Vaults in different models.
2. Switch to the model with the unsealer, and offer your unsealer `vault-autounseal-provides` integration: `juju offer vault:vault-autounseal-provides`
3. Switch to the model with the autounsealed Vault, and consume the integration: `juju consume mycloud:admin/dev.vault`
4. Continue as in the k8s instructions above.
=> feat: Auto-unseal

lib/charms/tls_certificates_interface/v3/tls_certificates.py, lib/charms/vault_k8s/v0/vault_autounseal.py, src/charm.py, tests/unit/test_charm.py
There's no need to infer the mount path, and adding it makes the interface more flexible.
This also bumps the libraries to their latest versions.
This conforms with the interface described in https://github.com/canonical/charm-relation-interfaces/tree/main/interfaces/vault_autounseal/v0
k8s charm version: https://github.com/canonical/vault-k8s-operator/pull/406
=> feat: include mount path in databag contents

charmcraft.yaml, src/charm.py, tests/integration/test_integration.py, tests/unit/test_charm.py
This change includes moving from using an action to authorize the charm to granting a user secret to authorizing a charm. The process is simply:
```shell
juju add-secret approle_authorization_token token=$VAULT_TOKEN
juju grant-secret approle_authorization_token vault-k8s
juju config vault-k8s approle_token_secret_id=$(juju show-secret approle_authorization_token | yq 'to_entries[]' | yq .key)
```
The documentation will need to be updated.
=> feat: Use juju secrets instead for authorize-charm 

pyproject.toml, tests/integration/helpers.py, tests/integration/test_integration.py
After publishing a new version of the tls requirer, the integration tests will fail. This change resolves those issues.
=> test: Fix integration tests for latest tls requirer

src/charm.py, tests/integration/test_integration.py
fixes https://github.com/canonical/vault-operator/issues/243
Not to lose the secret://modeluuid/standard_secret_id format of the secret ID which is required to access the secret in cross model relations we get the secret with the secret ID that was initially returned by add_secret and initially stored in the relation databag.
Bug reported in Juju https://bugs.launchpad.net/juju/+bug/2075153
=> fix: Access kv secret using secret ID

lib/charms/vault_k8s/v0/vault_kv.py, src/charm.py, tests/integration/vault_kv_requirer_operator/src/charm.py, tests/unit/test_charm.py
Fixes https://github.com/canonical/vault-operator/issues/244
**Note1**: Should not be merged before https://github.com/canonical/vault-k8s-operator/pull/450
**Note2**: This is a breaking change on the provider side, but since this is handled in the same PR in Vault I think it should be okay. No breaking changes on the requirer side by allowing it to set the egress subnet as string or as list.
Instead of using the `interfaces` of the network binding to configure the approle in vault we use the list of `egress_subnets`.
Juju describes the interfaces as:
```
A list of network interface details. This includes the information
about how the application should be configured (for example, what IP
addresses should be bound to).
```
While it describes the `egress_subnets` to be:
```
A list of …
```
=> fix: Uses egress subnet list to configure approle

lib/charms/vault_k8s/v0/vault_kv.py, src/charm.py, tests/unit/test_charm.py
This PR introduces to the machine charm the changes made to the k8s charm in this [PR](https://github.com/canonical/vault-k8s-operator/pull/455).
Vault KV secrets of a specific unit are removed when the unit relation departs
=> fix: Removes vault kv secret on relation broken event

src/charm.py, tests/unit/test_charm.py
- If the charm is deployed on a machine that has the vault snap already installed and running, it won't install it again even if a different version is required, a good example is when `juju refresh <charm>` is used.
In this PR we make sure the underlying machine has the required snap.
- This restarts vault if a new snap is installed so we start running using the new snap.
- Adds tests
=> fix: Install and run the new version of the snap on the machine when Vault is updated.

.gitignore, pyproject.toml, test-requirements.in, test-requirements.txt, tests/integration/conftest.py, tests/integration/helpers.py, tests/integration/test_integration.py
This allows the integration tests to be run independently, or as a smaller subset.
Although most of the dependencies have been removed, not all of them have. I tried to mark the remaining inter-dependencies with `@pytest.mark.dependency` from the `pytest-dependency` plugin. This will skip any tests which have not had their dependencies run.
Unfortunately, the best way I could find to have all the charms deployed right at the start was with the `test_deploy_all_the_things()` test which doesn't perform any assertions.
```
tox -e integration -- --model dev --charm_path ./vault_ubuntu-22.04-amd64.charm --kv_requirer_charm_path ./tests/integration/vault_kv_requirer_operator/vault-kv-requirer_ubuntu-22.04-amd64.charm -k test_given_vault_kv_requirer_related_when_create_secret_then_secret_is_creat …
```
=> test: Run integration tests independently

src/charm.py, src/machine.py, tests/integration/helpers.py, tests/integration/vault.py, tests/integration/vault_kv_requirer_operator/src/charm.py
k8s version: https://github.com/canonical/vault-k8s-operator/pull/465
Justification, copied from above:
- `Optional` was a poor choice of words. It doesn't fit well in all contexts and it conflicts with the already established meaning of an optional argument (you can have an optional argument that isn't optional).
- `Optional` also makes a lot less sense from an English perspective when it's a return value.
- It's easier to read (subjective)
- It's the new way, and new things are _always_ better,
- Also removes use of `Union`
=> refactor: Use `| None` instead of `Optional`

.github/renovate.json5, .github/workflows/integration-tests.yaml
Rollback concierge introduction to fix CI flakiness. Also prevent renovate from updating pytest-asyncio as it breaks integration tests.
=> fix: Fix CI flakiness by rolling back concierge and preventing pytest-asyncio updates

tests/integration/helpers.py, tests/integration/test_integration.py
This is a bad habit I have that I blame on Django.
Unfortunately, the ruff check for this is still not stable.
=> refactor: Use logger, not the root logger (logging)

.github/workflows/integration-tests.yaml
This steals @saltiyazan 's commit from #338 , as I need it to get the integration tests working for another PR.
Fixes an issue with the integration test workflow regarding tox installation.
=> build: Fix tox installation

src/charm.py, src/templates/kv_mount.hcl, tests/unit/fixtures.py, tests/unit/test_charm_configure.py
~~Needs #347~~
Removes the machine charm implementation of KV and uses the manager implemented in https://github.com/canonical/vault-k8s-operator/pull/571 instead.
=> refactor: Remove KV implementation and use manager instead

tox.ini
This forces tox to use the locked dependencies with uv.
=> fix: Use locked dependencies when running tox

tests/unit/fixtures.py, tests/unit/test_charm_configure.py
_Note_: This could not follow the pattern used in https://github.com/canonical/vault-k8s-operator/pull/579 because Python has a limit on the number of static nesting, and the syntax there (using commas), apparently, is just syntactic sugar for multiple nesting blocks. Therefore, I had to use `ExitStack()`. I think I actually like it more, because it keeps things to one line.
context:
Patchers made more sense when we were using unittest, and we had setup and teardown methods. Now that we've moved to pytest, we can use contextmanagers by yielding within the fixture.
This ensures that the patches are properly undone after each test.
=> refactor: Use contextmanagers instead of patchers

src/charm.py, tests/unit/fixtures.py, tests/unit/test_charm_create_backup_action.py, tests/unit/test_charm_list_backups_action.py, tests/unit/test_charm_restore_backup_action.py
Removes the machine charm specific implementation of backups, and makes use of the BackupManager introduced in https://github.com/canonical/vault-k8s-operator/pull/577
~~Depends on #352~~
=> refactor: remove the backup code from the machine charm

charmcraft.yaml, src/charm.py, tests/unit/fixtures.py, tests/unit/test_charm_bootstrap_raft_action.py
Implements bootstrapping raft via an action as per TE133.
The user experience is as follows:
Remove all but one unit.
```
juju remove-unit vault/1 vault/2 vault/3 vault/4
```
Run the bootstrap-raft action.
```
juju run vault/leader bootstrap-raft
```
Cleanup of the `peers.json` file is done automatically by Vault once the single-unit cluster recovers.
CharmHub docs to follow in a separate task.
=> feat: Implement bootstrap raft action

lib/charms/vault_k8s/v0/vault_helpers.py, src/charm.py
Introduces the same changes as in https://github.com/canonical/vault-k8s-operator/pull/578 to use the `vault_helper` lib.
Depends on https://github.com/canonical/vault-k8s-operator/pull/592
=> chore: Uses Vault helpers

.github/tics.yaml
This is an attempt to add the TIOBE static code analysis to the build.
There are very likely to be additional changes to this workflow, however, since it's difficult to test I'd like to get this first step merged to main, and then I can test additional changes using the workflow dispatch call.
This is based off SEC0024 and [this sample](https://github.com/canonical/ticsimg/blob/main/.github/workflows/tics_run_sh_ghaction_test.yml), with some minor tweaks:
- Use hashes to ensure workflows aren't changed from underneath us
- Set branchdir to what the docs suggested, although I'm not sure it's correct.
- Add a cron schedule to run this weekly, which was the most frequent suggested by SEC0024
=> build: add tiobe quality check workflow
