- CODEOWNERS
Adds the TLS team to CODEOWNERS
> chore: Add TLS team to CODEOWNERS

- .github/workflows/lint-pr.yaml
Adds PR linting validation to ensure consistent commit messages.
> chore: Adds PR linting validation

- lib/charms/operator_libs_linux/v1/snap.py
- src/charm.py
- test-requirements.txt
- tests/unit/test_charm.py
- tox.ini
Installs the Vault snap.
Note: Running the Vault service is coming up and is dependant on this PR being merged:
- https://github.com/canonical/snap-vault/pull/52
> feat: Installs vault snap

- icon.svg
Adds icon that will be used in Charmhub.
> docs: Add Charmhub icon

- lib/charms/operator_libs_linux/v2/snap.py
- src/charm.py
- tests/unit/test_charm.py
> chore: Bump snap lib to 2.3

- .github/workflows/integration-tests.yaml
bump juju version from 3.1 to 3.4
> chore: bump juju to 3.4

- tox.ini
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
> build: Remove warning for deprecated invocation

- tests/unit/test_charm.py
`patch()` calls at the `setUp` level only affect the calls in setUp (which is where the charm is initialized), but not the calls in `test_` methods.
`patch()` calls at the `TestCharm` level only affect the `test_` methods, and do not affect charm initialization.
This caused some incosistency and unreliability of the mocks, depending on when certain calls were made, and on multiple occasions the tests attempted to install snaps on my machine. By mocking the entire class (instead of just individual methods), and using a patcher with `start()`/`stop()` calls in `setUp()` and `tearDown()`, we are patching all the calls made in the test, and avoid letting calls slip through the cracks. It also avoids having patch calls at multiple different levels.
Please include a summary of the change. …
> refactor: Improve mock reliability

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/vault_k8s/v0/vault_tls.py
Manually updating the libs as #77 is not enabled yet.
> chore(deps): Update charm libs

- tests/unit/test_charm.py
Removes an unnecessary ignore annotation
> chore: Remove unnecessary ignore annotation

- tests/integration/test_integration.py
Prevents polluting the working directory and lets tox handle cleanup.
> build: Store temporary file in libjuju tmp directory

- .github/workflows/promote.yaml
> chore: add promote ci workflow

- pyproject.toml
- src/charm.py
- tests/integration/conftest.py
- tests/integration/test_integration.py
- tests/integration/vault.py
- tests/unit/test_charm.py
Uses TLS and secure verification, the CA certificate is passed to 
Provides the api address of the current Vault unit
Note for reviewers:
Commits [1](https://github.com/canonical/vault-operator/pull/158/commits/d8b6cf21915edc9a583589a7a11cf31a66c76516) and [2](https://github.com/canonical/vault-operator/pull/158/commits/8affacb89f8050ed724ff909d982de8aca139af3) contain the functionality
Commit [3](https://github.com/canonical/vault-operator/pull/158/commits/8795bd7d5a3eb09b4dd307017f5be997c1960bfd) fixes tox issues
> fix: Fixes Cos Agent configs

- .github/workflows/cla-check.yaml
Validate that code contributors have signed Canonical's License Agreement.
- https://ubuntu.com/legal/contributors
- https://github.com/canonical/has-signed-canonical-cla?tab=readme-ov-file
> chore: add CLA check

- src/charm.py
Static analysis is failing in #185 , this PR aims to fix the issues.
> fix: Fixes static analysis issues

- src/charm.py
- tests/unit/test_charm.py
Some messages that require user to take action sound like the charm is waiting rather than being blocked and dependent on user input/action.
> chore: Improves status messages for better UX

- .github/workflows/cla-check.yaml
Remove the CLA check action as it is causing CI issues. It is intermittently working and flagging PR's as being not being signed by contributors.
> chore: remove cla check

- src/charm.py
Reduces conflicts. I couldn't find a way to automate this, unfortunately. I expected to find it in ruff or isort.
> style: Sort global constants

- src/charm.py
This makes a minor simplification to the code, but is a nice refactor to have for some upcoming auto-unseal code.
> refactor: Return an `AppRole` object to simplify

- src/charm.py
> refactor: Consolidate code for setting Juju secret

- charmcraft.yaml
Some juju secret features and fixes that the charm depends on might not present in lower versions, we make the constraint a bit more specific.
3.1.8 is the current 3.1/stable.
> chore: Make juju constraints more specific in charmcraft.yaml

- .github/workflows/integration-tests.yaml
We use selfhosted runners to have more space to do our integration tests
> chore: selfhosted runners

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yaml
To avoid having separate workflow files for main and each release branch we run these workflows on release branches too.
> chore: Runs main CI workflows on release branches too

- .github/dependabot.yml
Adds dependabot config for the release branch
> chore: Adds dependabot config for the release branch

- lib/charms/vault_k8s/v0/vault_kv.py
- lib/charms/vault_k8s/v0/vault_tls.py
- pyproject.toml
- tests/integration/helpers.py
- tests/integration/test_integration.py
This PR consists of commits that have been approved and merged on main. The release branch could benefit from the integration test improvements.
> fix: Backport integration test and lib changes to the release branch

- src/charm.py
A small change to make sure we log the failed Vault authentication attempt instead of proceeding and failing on the API call.
> fix: Validate vault authentication

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- lib/charms/vault_k8s/v0/vault_tls.py
- src/charm.py
- tests/unit/certificates.py
> chore: Use tls lib V4.0

- pyproject.toml
- tests/integration/helpers.py
- tests/integration/test_integration.py
- tests/integration/vault.py
Checks for some common logging patterns to avoid.
> build: Add logging lint checks to ruff

- pyproject.toml
- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_integration.py
- tests/integration/vault_kv_requirer_operator/src/charm.py
- tests/unit/test_charm_configure.py
This change adds a pyright check to ensure that we add type hints to our code
> build: Enable pyright to check if type hints are missing

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- lib/charms/vault_k8s/v0/juju_facade.py
- lib/charms/vault_k8s/v0/vault_kv.py
- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- src/machine.py
- tests/unit/fixtures.py
Updates all charm libs, and associated code.
Also adds `is_accessible` to `machine.py` to satisfy the new interface.
> build: Update charm libs and associated charm code

- .github/workflows/main.yaml
Using versioned workflows will allow us to introduce breaking changes without breaking all the builds at once.
> build: Use versioned workflows

- tests/integration/test_integration.py
Add assertion for CA certificate presence and pin self-signed certificates revision
> test: Pin self-signed certificates revision
